server:
  port: 80
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: enjoytrip_springboot
  #datasource \uC124\uC815
  datasource:
    url: jdbc:mysql://localhost:3306/enjoytrip?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: root
    password: gjswo2679
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
  #Failed to start bean 'documentationPluginsBootstrapper'; error
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

#mybatis setting
mybatis:
  mapper-locations: mapper/**/*.xml
  type-aliases-package: com.ssafy.*.model

# logging
logging:
  level:
    root: info
    com.ssafy.ws.step3: debug
